#!/usr/bin/env sh

set -e

rootdir="$(pwd)"
zig_version="0.9.0-dev.1249+210ef5af8"

target="x86_64-windows-gnu"
target_and_cpu=$target-baseline

devkit="$rootdir/out/windows-devkit/zig+llvm+lld+clang-$target-$zig_version"

rm -rf "$devkit" "$devkit.zip"
mkdir -p "$devkit"

echo "copying devkit files..."
cp -R "$rootdir/out/$target_and_cpu/"* "$rootdir/out/zig-$target_and_cpu/"* "$devkit/"

echo "renaming libX.a to X.lib"
for f in $(find "$devkit/lib/"lib*.a); do
    dirname="$(dirname "$f")"
    basename="$(basename "$f")"
    new_name="$dirname/$(echo "$basename" | sed 's/^lib//' | sed 's/a$/lib/')"
    mv "$f" "$new_name"
done

echo "removing ld exes..."
rm "$devkit/bin/"*ld*.exe

echo "success, devkit located at:"
echo "$devkit"
